import { Assets, Sprite, Spritesheet, type SpritesheetData, type Texture } from 'pixi.js';
import { Chess } from 'chess.js';
import { animate, AnimationOptions } from 'motion';
import type { Engine } from '../engine';
import { squareToPixel } from '../coordinates';

import spritesheetData from '../../assets/sprites/sprites.json';
import spritesheetPath from '../../assets/sprites/sprites.png';

/**
 * The spritesheet is generated by TexturePacker.
 * @see {@link ../../assets/sprites/packer}
 * @see {@link https://pixijs.download/dev/docs/assets.Spritesheet.html}
 */
export async function loadPieceTextureAtlas(): Promise<Record<string, Texture>> {
  const atlasTexture = await Assets.load(spritesheetPath);
  const sheet = new Spritesheet(atlasTexture, spritesheetData as SpritesheetData);
  await sheet.parse();
  return sheet.textures;
}

// Motion config.
const SPRING_CONFIG: AnimationOptions = { type: 'spring' as const, stiffness: 180, damping: 22, mass: 1 };

// Get where every piece starts, and were every piece ends.
function getAnimationSources(chess: Chess): Map<string, string> | null {
  const lastMove = chess.history({ verbose: true }).at(-1);
  if (!lastMove) return null;

  const sources = new Map<string, string>([[lastMove.to, lastMove.from]]);

  // https://en.wikipedia.org/wiki/Castling#Description
  const row = lastMove.to[1];
  if (lastMove.isKingsideCastle()) {
    sources.set(`f${row}`, `h${row}`);
  } else if (lastMove.isQueensideCastle()) {
    sources.set(`d${row}`, `a${row}`);
  }

  return sources;
}

export function syncPieces(engine: Engine, chess: Chess, snap: boolean) {
  const { squareSize, textures, resources } = engine;

  resources.pieces.removeChildren();
  resources.animating.removeChildren();

  const sources = snap ? null : getAnimationSources(chess);

  for (const row of chess.board()) {
    for (const cell of row) {
      if (!cell) continue;

      const textureName = `${cell.color}${cell.type}.png`;
      const texture = textures[textureName];
      if (!texture) continue;

      const sprite = new Sprite({ texture, anchor: 0.5 });
      sprite.label = cell.type;
      sprite.scale.set(squareSize / texture.width);

      const target = squareToPixel(cell.square, squareSize, 'white', engine.boardOffset);
      const isAnimating = sources?.get(cell.square);

      if (isAnimating) {
        const start = squareToPixel(isAnimating, squareSize, 'white', engine.boardOffset);
        sprite.position.set(start.x, start.y);
        resources.animating.addChild(sprite);
        engine.animations.add(animate(sprite.position, target, SPRING_CONFIG));
      } else {
        sprite.position.set(target.x, target.y);
        resources.pieces.addChild(sprite);
      }
    }
  }
}
