steps:
  # Step 1: Install dependencies, sync versions, and build all static assets.
  # This runs our 'build-ci' script which builds all visualizers and
  # collects the artifacts into a single './build' directory.
  - name: "gcr.io/cloud-builders/npm"
    id: "build-all-visualizers"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        apt-get update && apt-get install -y jq
        npm install -g pnpm
        pnpm install
        node web/scripts/sync-version.js
        pnpm build-ci

  # Step 2: Publish the core package to NPM.
  # This runs after the build to ensure the package is up-to-date.
  - name: "gcr.io/cloud-builders/npm"
    id: "publish-to-npm"
    entrypoint: "bash"
    args: ["web/scripts/publish-core.sh"]
    waitFor: ["build-all-visualizers"]
    secretEnv: ["NPM_TOKEN"]

  # Step 3: Deploy the collected artifacts to Google Cloud Storage.
  # 'rsync -d' syncs the directory and deletes any files in the destination
  # that are not in the source, We probably want to change this to keep versions
  # once we figure out a decent versioning scheme.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-to-gcs"
    entrypoint: "gsutil"
    args:
      - "-m"
      - "rsync"
      - "-d"
      - "-r"
      - "./build"
      - "gs://$_BUCKET_NAME/episode-visualizers"
    waitFor: ["publish-to-npm"]

substitutions:
  _BUCKET_NAME: "kaggle-static"

availableSecrets:
  secretManager:
    - versionName: projects/kaggle-cicd/secrets/npm-token-kaggle-environments/versions/latest
      env: "NPM_TOKEN"

tags: ["kaggle-environments", "visualizer-deployment", "npm-publish"]
