steps:
  # Step 1: Install dependencies and build all static assets.
  # This runs our 'build-ci' script which builds all visualizers and
  # collects the artifacts into a single './build' directory.
  # If this gets much more complicated, we should make a bash or docker file.
  - name: "gcr.io/cloud-builders/npm"
    id: "build-all-visualizers"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        apt-get update && apt-get install -y jq
        npm install -g pnpm
        pnpm install
        pnpm build-ci

  # Step 2: Deploy the collected artifacts to Google Cloud Storage.
  # 'rsync -d' syncs the directory and deletes any files in the destination
  # that are not in the source, We probably want to change this to keep versions
  # once we figure out a decent versioning scheme.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-to-gcs"
    entrypoint: "gsutil"
    args:
      - "-m"
      - "rsync"
      - "-d"
      - "-r"
      - "./build"
      - "gs://$_BUCKET_NAME/episode-visualizers"
    waitFor: ["build-all-visualizers"]

substitutions:
  _BUCKET_NAME: "kaggle-static"

tags: ["kaggle-environments", "visualizer-deployment"]
