import { test, expect } from '@playwright/test';

test.describe('Shogi Visualizer', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('renders the game', async ({ page }) => {
    await expect(page.locator('.renderer-container')).toBeVisible();
    await expect(page.locator('.renderer-container canvas')).toBeVisible();

    const players = page.locator('.header .player');
    await expect(players.first()).toBeVisible();
    expect(await players.count()).toBe(2);

    // Both komadai (hand panels) are mounted.
    expect(await page.locator('.hand').count()).toBe(2);

    await expect(page.locator('.status-container')).toBeVisible();
  });

  test('displays correct game state at mid-game', async ({ page }) => {
    const slider = page.locator('input[type="range"]');
    await slider.waitFor({ state: 'visible' });

    const maxValue = await slider.getAttribute('max');
    const midStep = Math.floor(parseInt(maxValue || '0') / 2);
    await slider.fill(String(midStep));
    await page.waitForTimeout(200);

    await expect(page.locator('.renderer-container canvas')).toBeVisible();
    await expect(page.locator('.status-container')).toBeVisible();
  });

  test('displays winner status at final step', async ({ page }) => {
    const slider = page.locator('input[type="range"]');
    await slider.waitFor({ state: 'visible' });

    const maxValue = await slider.getAttribute('max');
    await slider.fill(maxValue || '0');
    await page.waitForTimeout(200);

    await expect(page.locator('.status-container').filter({ hasText: /Game over/i })).toBeVisible();
    await expect(page.locator('.winner-banner.active').filter({ hasText: /WINS|Game over/i })).toBeVisible();
  });

  test('shows forfeit reason at final step', async ({ page }) => {
    // Swap the natural test replay for a forfeit variant via postMessage.
    // Same dev server, no config change — see visualizer/default/replays/
    // test-forfeit-replay.json (generated by the pilot script).
    const injected = await page.evaluate(async (replayUrl) => {
      const resp = await fetch(replayUrl);
      if (!resp.ok) return { ok: false, status: resp.status };
      const replay = await resp.json();
      window.postMessage({ replay }, '*');
      return { ok: true, status: 200 };
    }, '/test-forfeit-replay.json');
    test.skip(!injected.ok, `test-forfeit-replay.json not available (HTTP ${injected.status})`);

    // Wait for the replay swap to propagate, then drive to the last step.
    await page.waitForTimeout(300);
    const slider = page.locator('input[type="range"]');
    await slider.waitFor({ state: 'visible' });
    const maxValue = await slider.getAttribute('max');
    await slider.fill(maxValue || '0');
    await page.waitForTimeout(200);

    // The forfeit reason line appears somewhere on the page. Match loosely
    // so per-game phrasing (illegal move / TIMEOUT / ERROR) all pass.
    await expect(
      page.getByText(/wins by default|forfeited|illegal move|ran out of time|failed to produce/i).first()
    ).toBeVisible();
  });
});
